version: '3'

services:

  nginx:
    image: nginx:1.17-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - ../:/app/
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'slamquiz'
      POSTGRES_DB: 'slamquiz'     
      POSTGRES_PASSWORD: 'db_password'
